# Generated by Django 3.0.7 on 2022-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
