# Generated by Django 3.0.7 on 2022-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220802_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
