# Generated by Django 3.0.7 on 2022-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220802_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('kitchen', models.IntegerField()),
                ('maintenance', models.CharField(max_length=50)),
                ('internetbills', models.IntegerField(null=True)),
                ('gasbill', models.IntegerField(null=True)),
                ('waterbills', models.IntegerField(null=True)),
                ('electricitybill', models.IntegerField(null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
