# Generated by Django 3.0.7 on 2022-08-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
    ]
