# Generated by Django 3.0.7 on 2022-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20220804_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('wages', models.IntegerField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepingPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('investment', models.IntegerField(null=True)),
                ('PartnerPorfit', models.IntegerField(null=True)),
                ('CompanyProfit', models.IntegerField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
