# Generated by Django 3.0.7 on 2022-08-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_employee_labours_sleepingpartners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepingpartners',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
