# Generated by Django 3.0.7 on 2022-08-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20220807_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='weight',
            field=models.CharField(choices=[('kg', 'KG'), ('man', 'MAN')], default='kg', max_length=6),
        ),
    ]
