# Generated by Django 3.0.7 on 2022-08-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20220830_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='weights',
            field=models.CharField(choices=[('kg', 'KG'), ('man', 'MAN')], default='kg', max_length=6),
        ),
    ]
