# Generated by Django 3.0.7 on 2022-08-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_saleitem_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='weights',
        ),
    ]
